-- 코드를 입력하세요
SELECT CRCR.CAR_ID,
       CRCR.CAR_TYPE,
       FLOOR(CRCR.DAILY_FEE * (1-(CRCDP.DISCOUNT_RATE/100)) * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR CRCR
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP
ON CRCR.CAR_TYPE = CRCDP.CAR_TYPE
WHERE CRCR.CAR_TYPE IN ('SUV', '세단')
AND CRCR.CAR_ID NOT IN (SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-11-30'
  AND END_DATE >= '2022-11-01')
  AND CRCDP.DURATION_TYPE = '30일 이상'
  AND FLOOR(CRCR.DAILY_FEE * (1-(CRCDP.DISCOUNT_RATE/100)) * 30) BETWEEN 50000 AND 2000000
ORDER BY FEE DESC,
         CRCR.CAR_TYPE ASC,
         CRCR.CAR_ID DESC
  


