-- 코드를 입력하세요
# 1. IN에 존재하는데 OUT에 존재하지않는
# 2. IN보호시작일오름차순상위3개
SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AI
LEFT OUTER JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.ANIMAL_ID IS NULL
ORDER BY AI.DATETIME ASC
LIMIT 3